## What is NumPy?

**NumPy** (Numerical Python) is a powerful library in Python used for **scientific and numerical computing**. It makes working with numbers and large datasets much easier and faster.

---

#### Key Features of NumPy:

- **Main Tool :** It provides a special object called **`ndarray`** (n-dimensional array), which lets you store and work with large collections of numbers in a very efficient way

- You can do **math operations** like addition, subtraction, multiplication, and more on whole arrays at once

- It supports **logical operations**, **sorting**, **filtering**, and **changing shapes** of arrays easily

- It includes tools for:
  - **Linear Algebra** (like solving equations or matrix multiplication)

  - **Statistics** (like mean, median, standard deviation)

  - **Random number generation** (for simulations or testing)

  - **Fourier transforms** (used in signal processing)

  - **Input/Output operations** (reading or writing data)

---

#### Why use NumPy?

- It's **much faster** than normal Python lists when handling lots of numbers

- It's the **foundation** for other libraries like **Pandas**, **SciPy**, and even machine learning libraries like **TensorFlow**.


### **NumPy Arrays vs Python Sequences (Lists/Tuples)**

#### **Comparison Table**

| Feature | NumPy Array | Python Sequence (List/Tuple) |
|--------|-------------|-------------------------------|
| **Size** | Fixed when created | Can grow or shrink dynamically |
| **Data Type** | All elements must be of the same type | Elements can be of different types |
| **Speed** | Much faster for large data and operations | Slower for large data |
| **Memory** | Uses less memory (elements stored in same type) | Uses more memory (stores metadata per element) |
| **Math Operations** | Supports direct operations like `+`, `*`, `sin`, `mean`, etc. on arrays | Needs loops or list comprehensions |
| **Used in Libraries** | Common in scientific packages (like Pandas, Scikit-learn, TensorFlow) | Not optimized for such use cases |

---

#### **Why Prefer NumPy Arrays ?**

- NumPy arrays allow **fast**, **vectorized** operations (no need for loops)

- Ideal for **scientific and mathematical computing**

- Most modern Python data libraries convert your list/tuple into NumPy arrays internally

- Working with NumPy means **less code, faster execution**, and better performance.

---

#### **Note :**

**If you change the size of a NumPy array (e.g., adding/removing elements), it will **create a new array** and delete the original. This is different from lists which allow dynamic resizing**


#### **Creating Numpy Arrays**

**Importing the numpy library**

In [1]:
import numpy as np

In [2]:
# 1D Array

arr = np.array([1,2,3,4])
print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# 2D array 

arr1 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr1)


[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# 3D Array

arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Creating the array of different**

In [5]:
# float array
a = np.array([1,2,3,4],dtype=float)
print(a)

[1. 2. 3. 4.]


In [6]:
# bool

b = np.array([1,2,3],dtype=bool)
print(b)

[ True  True  True]


In [7]:
# complex

c = np.array([1,2,3],dtype=complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j]


**Using arange function**

In [8]:
np.arange(1,21)   # last number ( 21 ) is not included

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
np.arange(1,21,2)  # For jumps

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

**Using reshape function**

In [10]:
a = np.arange(1,11)
print(a)

a.reshape(2,5)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
a.reshape(5,2)   # But the product of number (5,2) must be equal to number of elements 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

**Using ones and zeros function**

In [12]:
# ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# zeros

np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Using random function**

In [14]:
# Generate the random number

np.random.random((3,6))

array([[0.56065377, 0.3204148 , 0.65181266, 0.88761619, 0.51752512,
        0.14606362],
       [0.30299303, 0.20794836, 0.6571819 , 0.8676812 , 0.96724491,
        0.36661728],
       [0.25379793, 0.11544131, 0.25329968, 0.36052664, 0.9110136 ,
        0.48844534]])

**Using linspace function**

Give me numbers from A to B, with equal gaps, total C numbers

In [15]:
# np.linspace(lower_range, upper_range, count_of_items)

np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

**Using indentity function**

In [16]:
np.identity(4)  # 4 means 4 x 4  identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### **Array Atributes**

**Creating the array required**

In [17]:
a1 = np.arange(10)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
a2 = np.arange(12,dtype=float).reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [19]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


**ndim** : it shows the number of dimensions

In [20]:
a1.ndim

1

In [21]:
a2.ndim

2

In [22]:
a3.ndim

3

**shape** : tell the shape of array , means row and columns

In [23]:
print(a1)
print()
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]

(10,)


In [24]:
print(a2)
print()
print(a2.shape)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

(3, 4)


In [25]:
print(a3)
print()
print(a3.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

(2, 2, 2)


**size** : it tell us the number of items in array

In [26]:
a3.size

8

In [27]:
a2.size

12

**itemsize** : tell us that , how much space an item is occupying in memory ( tell in bytes)

In [28]:
a1.itemsize   # in bytes

8

In [29]:
a2.itemsize

8

In [30]:
a3.itemsize

8

**dtype** : tell the data type of items in array

In [31]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


##### **Changing data type**

In [32]:
# astype

a = np.arange(10).reshape(2,5)
print(a)

a.astype(np.int32)



[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int32)

#### **Operations on Array**

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [34]:
print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


##### **Scalar Operations**

**Arithemetic operations**

In [35]:
a1 * 2

# All will work , / , + , - 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

**Relationship operations**

In [36]:
a2 > 13

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

##### **Vector Operations**

In [37]:
# arithmetic 

a1 + a2  # itemwise addition

# Here also all will work

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#### **Array Functions**

In [38]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[61., 43., 95.],
       [83., 55., 17.],
       [85., 50., 41.]])

**max , min , sum , prod**

In [39]:
# max

print(np.max(a1))

95.0


In [40]:
# min

print(np.min(a1))

17.0


In [41]:
# sum

print(np.sum(a1))

530.0


In [42]:
# prod

print(np.prod(a1))

3369646835431250.0


In [43]:
# For operations on row or column we have to change the axis
# axis --> 0 = column
# axis --> 1 = rows

print(np.max(a1,axis=1))  # for rows

# same for min , sum , and prod

[95. 83. 85.]


**mean , std , median , var**

In [44]:
# mean

print(np.mean(a1))

58.888888888888886


In [45]:
# median

print(np.median(a1))

55.0


In [46]:
# std

print(np.std(a1))

23.553459026197523


In [47]:
# varaince

print(np.var(a1))

554.7654320987655


**Trigonometric functions**

In [48]:
print(np.sin(a1))

# Other all will work , but not much used in data science

[[-0.96611777 -0.83177474  0.68326171]
 [ 0.96836446 -0.99975517 -0.96139749]
 [-0.17607562 -0.26237485 -0.15862267]]


**dot function**

In [49]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2)
print()
print(a3)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [50]:
# dot product

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

**log and exponents**

In [51]:
# log

np.log(a1)

array([[4.11087386, 3.76120012, 4.55387689],
       [4.41884061, 4.00733319, 2.83321334],
       [4.44265126, 3.91202301, 3.71357207]])

In [52]:
# Exponents

np.exp(a1)

array([[3.10429794e+26, 4.72783947e+18, 1.81123908e+41],
       [1.11286375e+36, 7.69478527e+23, 2.41549528e+07],
       [8.22301271e+36, 5.18470553e+21, 6.39843494e+17]])

**round , floor , ceil**

In [53]:
# round 
a = np.random.random((2,3))*100
print(a)

np.round(a)

[[64.59313214 37.51614727 92.86938098]
 [16.58885428 97.53063889 45.11200747]]


array([[65., 38., 93.],
       [17., 98., 45.]])

In [54]:
np.floor(a)

array([[64., 37., 92.],
       [16., 97., 45.]])

In [55]:
np.ceil(a)

array([[65., 38., 93.],
       [17., 98., 46.]])

#### **Indexing and Slicing**

In [56]:
a1 = np.arange(15)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [57]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Indexing**

In [58]:
print(a1[-1])

# same as we learn in python

14


For 2D

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
print(a2[1,2])

6


In [61]:
print(a2[2,3])

print(a2[1,0])

11
4


For 3D

In [62]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
print(a3[1,0,1])

5


In [64]:
print(a3[0,1,0])

2


**Slicing**

For 1D

In [65]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
print(a1[3:6])

[3 4 5]


In [67]:
print(a1[9:14:2])   # jumps

[ 9 11 13]


For 2D

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
print(a2[:,2])

[ 2  6 10]


In [84]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [ ]:
print(a2[::2,::3])   # this was little tricky

[[ 0  3]
 [ 8 11]]


In [94]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
print(a2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [98]:
print(a2[1:2,::3])

[[4 7]]


In [101]:
print(a2[0:2,1::2])

[[1 3]
 [5 7]]


For 3D

In [104]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
print(a3[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [107]:
print(a3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [109]:
print(a3[0,1,:])

[3 4 5]


In [110]:
print(a3[1,:,1])

[10 13 16]


In [111]:
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [113]:
print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


#### **Loops**

For 1D

In [117]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


For 2D

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
    print(i)  # one time , one row

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


For 3D

In [118]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
    print(i)  # one time , one 2d array

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


**To iterate on each items**

In [120]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


#### **Reshaping the array**

**Reshape**

In [121]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
a1.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Transpose**

In [125]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2.transpose()   # or you can write --->  a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

**Ravel**

Convert any dimension array to 1D

In [128]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### **Stacking**

**Note : Size of both array must be same**

**Horizontal Stacking**

In [135]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print()
print(a5)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [136]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

**Vertical Stacking**

In [137]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### **Spliting**

**Horizontal Spliting**

In [138]:
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [143]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

**Vertical Spliting**

In [144]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [146]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]