## **Numpy**

#### **Some Important Function of Numpy**

In [1]:
import numpy as np

In [2]:
ar = np.random.randint(1,100,15)
print(ar)


[99 33 75 12 12 63  6 19 55  1 71 26 64 44 44]


In [3]:
ar1 = np.random.randint(1,100,24).reshape(6,4)
print(ar1)

[[69 44 46 76]
 [72 95 21 78]
 [13 30 66  9]
 [25 24 55  6]
 [63 36 76 93]
 [67 14 13 68]]


#### **np.sort( )**

The `np.sort()` function in NumPy is used to sort an array in ascending order

**What it does:**

- Returns a sorted copy of the input array

- It does not sort in-place (original array remains unchanged)

- By default, it sorts along the last axis (axis=-1)

In [4]:
print(np.sort(ar))

[ 1  6 12 12 19 26 33 44 44 55 63 64 71 75 99]


In [5]:
print(np.sort(ar1))   # By default row wise sorting

[[44 46 69 76]
 [21 72 78 95]
 [ 9 13 30 66]
 [ 6 24 25 55]
 [36 63 76 93]
 [13 14 67 68]]


**For Column wise**

In [6]:
print(np.sort(ar1,axis=0))

[[13 14 13  6]
 [25 24 21  9]
 [63 30 46 68]
 [67 36 55 76]
 [69 44 66 78]
 [72 95 76 93]]


**To sort in descending order**

In [7]:
print(np.sort(ar)[::-1])

[99 75 71 64 63 55 44 44 33 26 19 12 12  6  1]


#### **np.append( )**

The `np.append()` function is used to add values to the end of an array

**Notes :**

- If axis=None, both arrays are flattened before appending

- The shapes must match if appending along a specific axis

In [8]:
np.append(ar,200)

array([ 99,  33,  75,  12,  12,  63,   6,  19,  55,   1,  71,  26,  64,
        44,  44, 200])

In [9]:
np.append(ar1,np.random.random((ar1.shape[0],1)),axis=1)

array([[6.90000000e+01, 4.40000000e+01, 4.60000000e+01, 7.60000000e+01,
        2.93500994e-01],
       [7.20000000e+01, 9.50000000e+01, 2.10000000e+01, 7.80000000e+01,
        2.30515619e-01],
       [1.30000000e+01, 3.00000000e+01, 6.60000000e+01, 9.00000000e+00,
        9.46718678e-01],
       [2.50000000e+01, 2.40000000e+01, 5.50000000e+01, 6.00000000e+00,
        8.79666005e-01],
       [6.30000000e+01, 3.60000000e+01, 7.60000000e+01, 9.30000000e+01,
        9.21679489e-03],
       [6.70000000e+01, 1.40000000e+01, 1.30000000e+01, 6.80000000e+01,
        6.67872854e-01]])

#### **np.concatenate**

**The `np.concatenate()` function is used to join two or more arrays along an existing axis**

**Key Points :**

- Shapes must match along the axis you concatenate

- It does not flatten arrays (unlike np.append() when axis=None)

- Returns a new array (not in-place)

In [10]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)  # column wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

#### **np.unique**

**The `np.unique()` function is used to find unique elements of an array. It can also return sorted unique values, their indices, and counts**

**Parameters :**

- arr → Input array

- return_index → If True, returns indices of the first occurrence of each unique value

- return_inverse → If True, returns indices to reconstruct original array

- return_counts → If True, returns count of each unique element

In [13]:
e = np.array([1,1,1,2,2,2,3,3,3,4,4,5,5])

print(np.unique(e))

[1 2 3 4 5]


#### **np.expand( )**

**`np.expand_dims` is used to add a new axis (dimension) to a NumPy array at a specified position.
This is useful when you want to reshape data for operations like broadcasting or feeding it into models (like in TensorFlow or PyTorch)**

In [ ]:
a = np.random.randint(1,50,10)
print(a)

print(np.expand_dims(a,axis=0))  # column wise

print(np.expand_dims(a,axis=0).shape)  # shape 

[49 11 36 39 22 37 49 48 15 48]
[[49 11 36 39 22 37 49 48 15 48]]
(1, 10)


In [ ]:
print(np.expand_dims(a,axis=1))  # Row wise 
print()
print(np.expand_dims(a,axis=1).shape)

[[22]
 [ 2]
 [49]
 [43]
 [ 8]
 [ 8]
 [24]
 [27]
 [38]
 [22]]

(10, 1)


#### **np.where( )**

**`np.where` is a powerful function in NumPy used for conditional filtering and element-wise selection**

In [41]:
# Example : Find all indices with value greater than 50
print(a)

np.where(a > 30) # returns index positions

[49 11 36 39 22 37 49 48 15 48]


(array([0, 2, 3, 5, 6, 7, 9]),)

**Second Way to use it**

**np.where( condition , true , false  )**

In [48]:
print(a)

# replacing all values > 50 with 0

np.where(a > 30, 0, a)

[49 11 36 39 22 37 49 48 15 48]


array([ 0, 11,  0,  0, 22,  0,  0,  0, 15,  0])

In [ ]:
# Example : Replacing all even numbers with 0 

np.where(a % 2 == 0, 0, a)

array([49, 11,  0, 39,  0, 37, 49,  0, 15,  0])

#### **np.argmax( )**

**`np.argmax` is a NumPy function that returns the index of the maximum value in an array**

In [52]:
print(a)

print(np.argmax(a))

[49 11 36 39 22 37 49 48 15 48]
0


In [53]:
print(ar1)

[[69 44 46 76]
 [72 95 21 78]
 [13 30 66  9]
 [25 24 55  6]
 [63 36 76 93]
 [67 14 13 68]]


In [54]:
print(np.argmax(ar1,axis=0)) # Column wise

[1 1 4 4]


In [55]:
print(np.argmax(ar1,axis=1)) # Row wise

[3 1 2 2 3 3]


**Same is there for minimum**

**`np.argmin( )`**

In [57]:
print(a)

print()

print(np.argmin(a))

[49 11 36 39 22 37 49 48 15 48]

1


#### **np.cumsum( )**

**`np.cumsum()` stands for "cumulative sum" in NumPy**
**It returns an array where each element is the sum of all previous elements in the input array (including itself)**

In [58]:
print(ar)

[99 33 75 12 12 63  6 19 55  1 71 26 64 44 44]


In [59]:
np.cumsum(ar)

array([ 99, 132, 207, 219, 231, 294, 300, 319, 374, 375, 446, 472, 536,
       580, 624])

**Same there is : np.cumprod( )**

In [60]:
print(ar)

[99 33 75 12 12 63  6 19 55  1 71 26 64 44 44]


In [63]:
print(np.cumprod(ar))

[                  99                 3267               245025
              2940300             35283600           2222866800
          13337200800         253406815200       13937374836000
       13937374836000      989553613356000    25728393947256000
  1646617212624384000 -1335818939365310464 -3435801110945005568]


#### **np.percentile()**

**`np.percentile()` is a NumPy function used to find the value below which a given percentage of data falls**

In [64]:
print(ar)

[99 33 75 12 12 63  6 19 55  1 71 26 64 44 44]


In [ ]:
print(np.percentile(ar,100))

print(np.percentile(ar,0))

print(np.percentile(ar,50))

99.0
1.0
44.0


#### **np.histogram( )**

**`np.histogram()` is a NumPy function used to compute the histogram of a dataset — that means it counts how many values fall into each range (bin)**

In [69]:
ar

array([99, 33, 75, 12, 12, 63,  6, 19, 55,  1, 71, 26, 64, 44, 44])

In [75]:
np.histogram(ar,bins=10,range=(0,100))

(array([2, 3, 1, 1, 2, 1, 2, 2, 0, 1]),
 array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]))

#### **np.corrcoef( )**

**`np.corrcoef()` is a NumPy function that calculates the Pearson correlation coefficient between two or more variables**


In [78]:
salary = np.random.randint(1000,10000,10)
exp = np.random.randint(1,10,10)

print(salary)
print(exp)

[2228 4764 6913 1528 8417 8752 4588 4805 4582 6853]
[3 2 7 1 5 1 2 4 2 9]


In [79]:
np.corrcoef(salary,exp)

array([[1.        , 0.41286771],
       [0.41286771, 1.        ]])

#### **np.isin( )**

**np.isin() is a NumPy function that checks if elements in one array exist in another array**

**It returns a Boolean array of the same shape as the first input**

In [ ]:
items = [i for i in range(1,11)] # items one to ten

np.isin(ar,items)

array([False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False])

In [84]:
ar[np.isin(ar,items)]

array([6, 1])

#### **np.flip( )**

**`np.flip()` is a NumPy function that reverses the order of elements in an array along the specified axis**

In [85]:
ar

array([99, 33, 75, 12, 12, 63,  6, 19, 55,  1, 71, 26, 64, 44, 44])

In [86]:
np.flip(ar)

array([44, 44, 64, 26, 71,  1, 55, 19,  6, 63, 12, 12, 75, 33, 99])

**For 2D**

In [87]:
ar1

array([[69, 44, 46, 76],
       [72, 95, 21, 78],
       [13, 30, 66,  9],
       [25, 24, 55,  6],
       [63, 36, 76, 93],
       [67, 14, 13, 68]])

In [88]:
np.flip(ar1)

array([[68, 13, 14, 67],
       [93, 76, 36, 63],
       [ 6, 55, 24, 25],
       [ 9, 66, 30, 13],
       [78, 21, 95, 72],
       [76, 46, 44, 69]])

In [89]:
# For Row wise flipping
np.flip(ar1,axis=1)

array([[76, 46, 44, 69],
       [78, 21, 95, 72],
       [ 9, 66, 30, 13],
       [ 6, 55, 24, 25],
       [93, 76, 36, 63],
       [68, 13, 14, 67]])

In [90]:
# For column wise flipping
np.flip(ar1,axis=0)

array([[67, 14, 13, 68],
       [63, 36, 76, 93],
       [25, 24, 55,  6],
       [13, 30, 66,  9],
       [72, 95, 21, 78],
       [69, 44, 46, 76]])

#### **np.put( )**

**`np.put()` is a NumPy function used to set specific values at specific indices in a flattened version of the array**

In [91]:
ar

array([99, 33, 75, 12, 12, 63,  6, 19, 55,  1, 71, 26, 64, 44, 44])

In [93]:
np.put(ar,[0,1],[100,40])  # This function makes permenent change
ar

array([100,  40,  75,  12,  12,  63,   6,  19,  55,   1,  71,  26,  64,
        44,  44])

#### **np.delete( )**

**np.delete( ) is a NumPy function used to remove elements from a NumPy array along a specified axis**

In [94]:
ar

array([100,  40,  75,  12,  12,  63,   6,  19,  55,   1,  71,  26,  64,
        44,  44])

In [96]:
np.delete(ar,0)

array([40, 75, 12, 12, 63,  6, 19, 55,  1, 71, 26, 64, 44, 44])

In [99]:
ar

array([100,  40,  75,  12,  12,  63,   6,  19,  55,   1,  71,  26,  64,
        44,  44])

In [102]:
np.delete(ar,[i for i in range(0,10)])

array([71, 26, 64, 44, 44])

### **Set Functions**

| Function           | Description                                                 |
| ------------------ | ----------------------------------------------------------- |
| `np.intersect1d()` | Elements common to both arrays                              |
| `np.setdiff1d()`   | Elements in `a` but not in `b`                              |
| `np.setxor1d()`    | Elements in `a` or `b` but not both (symmetric difference)  |
| `np.union1d()`     | All unique elements from both arrays                        |


In [107]:
m = np.array([i*2 for i in range(1,11)])
n = np.array([i*2 for i in range(11,21)])

print(m,n)

[ 2  4  6  8 10 12 14 16 18 20] [22 24 26 28 30 32 34 36 38 40]


**union1d( )**

In [108]:
np.union1d(m,n)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

**intersect1d( )** 

In [109]:
np.intersect1d(m,n)

array([], dtype=int64)

**setdiff1d( )**

In [110]:
np.setdiff1d(m,n)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [111]:
np.setdiff1d(n,m)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

**setxor1d( )**

In [112]:
np.setxor1d(m,n)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

#### **np.clip( )**

**`np.clip()` is a NumPy function used to limit the values in an array**

**It "clips" (restricts) all values below a minimum and above a maximum to the given range**

In [115]:
ar

array([100,  40,  75,  12,  12,  63,   6,  19,  55,   1,  71,  26,  64,
        44,  44])

In [119]:
np.clip(ar,a_min=25,a_max=70)

array([70, 40, 70, 25, 25, 63, 25, 25, 55, 25, 70, 26, 64, 44, 44])